env:
  node: true
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  # "no-console": ["error",
  #   {
  #     allow: ["warn", "error"]
  #   }],
  "no-trailing-spaces": "error",
  "react/prop-types": "error",
  "no-unused-vars": "error",
  "no-undef": "error"
}
settings:
  react:
    version: detect


