version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/usr/src/app:rw
    # depends_on:
    #   - "db"
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
