version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/usr/src/app:rw
    depends_on:
      - "db"
    environment:
      PGUSER: ${DB_USER}
      PGHOST: ${DB_HOST}
      PGPASSWORD: ${DB_PASSWORD}
      PGDATABASE: ${DB_NAME}
      PGPORT: 5432
    entrypoint:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "nodemon",
        "app.js"
      ]      
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
