FROM node:14.15.1-stretch
WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install

# Install nodemon to reload server on changes
RUN npm install nodemon -g

EXPOSE 5000
CMD [ "nodemon", "app.js" ]
