run-dev:
	docker-compose -f docker-compose.yaml -f docker-compose-debug.yaml up --build -d backend db
run-pgadmin:
	docker-compose -f docker-compose.yaml -f docker-compose-debug.yaml up --build -d pgadmin
down:
	docker-compose -f docker-compose.yaml -f docker-compose-debug.yaml down -v
