env:
  node: true
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
    # "no-console": ["error",
    #   {
    #     allow: ["warn", "error"]
    #   }],
    "indent":
      [
        "warn",
        4,
        {
          "SwitchCase": 1,
          "VariableDeclarator": "first",
          "ArrayExpression": "first",
          "ObjectExpression": 1,
          "ImportDeclaration": 1,
          "ignoreComments": false,
        },
      ],
    "no-trailing-spaces": "error",
    "react/prop-types": "error",
    "no-unused-vars": "error",
    "no-undef": "error",
  }
settings:
  react:
    version: detect
