name: Docker Build Backend

on:
  push:
    branches: 
      - main
    paths:
      - "backend/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2          
      -
        name: Build and push backend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: techotron/sre-resources-backend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
